#pragma once

#include <stdint.h>

// Types
enum GameObject_Types : uint32_t {
	GAMEOBJECT_NONE,
	GAMEOBJECT_PLAYER,
	GAMEOBJECT_ASTEROID,
	GAMEOBJECT_FPS_DISPLAY,
	GAMEOBJECT_GAMEOVERLAY,
	GAMEOBJECT_NUM
};
